name: Java CI with Maven
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: Root@123  # Set a root password
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'oracle'
        architecture: x64
    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h localhost -uroot -pRoot@123 --silent; do
          echo 'waiting for mysql to be connectable...'
          sleep 10
        done
    - name: Create Database
      run: |
        mysql -h localhost -uroot -pRoot@123 -e "CREATE DATABASE feedify;"
        mysql -h localhost -uroot -pRoot@123 -e "CREATE USER 'feedify_admin'@'%' IDENTIFIED BY 'Admin@123';"
        mysql -h localhost -uroot -pRoot@123 -e "GRANT ALL PRIVILEGES ON feedify.* TO 'feedify_admin'@'%';"
        mysql -h localhost -uroot -pRoot@123 -e "FLUSH PRIVILEGES;"
    - name: Build with Maven
      run: cd backend && mvn clean install
    - name: Test with Maven
      run: cd backend && mvn test