name: Java CI with Maven
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'oracle'
        architecture: x64
    - name: Build with Maven
      run: cd backend && mvn clean install
      
      
  # formatting:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4 # v2 minimum required
  #     - uses: axel-op/googlejavaformat-action@v3
  #       with:
  #         args: "--replace"
  #         skip-commit: true
  #     - name: Print diffs
  #       run: cd backend && git --no-pager diff --exit-code

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'oracle'
          architecture: x64
      - name: Test with Maven
        run: cd backend && mvn test